default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: ""

test:
  <<: *default
  database: ""

production:
  <<: *default
  database: ""
