default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: /dev/null

test:
  <<: *default
  database: /dev/null

production:
  <<: *default
  database: /dev/null
